name: FG-Forge-Updater

description: Publish a Build on FantasyGrounds Forge

inputs:
  release-channel:
    description: 'The release channel to target ("Live", "Test", or "None") Default: "Live"'
    required: false
    default: 'Live'
  item-id:
    description: The item number from the FG Forge Store
    required: true
  username:
    description: Your FG Forge username
    required: true
  password:
    description: Your FG Forge username
    required: true
  file-path:
    description: File path of the ext or mod file
    required: true
  update-readme:
    description: 'Replace the Forge description with README.md? ("TRUE", "FALSE") Default: "TRUE"'
    required: false
    default: 'TRUE'

runs:
  using: composite

  steps:
    - uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d
      with:
        egress-policy: audit

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        repository: bmos/FG-Forge-Updater
        ref: v2
        path: fg-updater-internal

    - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78
      with:
        python-version: 3.14
        activate-environment: true
        working-directory: fg-updater-internal

    - run: uv sync --upgrade
      shell: bash
      working-directory: fg-updater-internal

    - run: uv run patchright install --with-deps
      shell: bash
      working-directory: fg-updater-internal

    - run: mv ${{ inputs.file-path }} fg-updater-internal/${{ inputs.file-path }}
      shell: bash

    - env:
        FG_RELEASE_CHANNEL: ${{ inputs.release-channel }}
        FG_ITEM_ID: ${{ inputs.item-id }}
        FG_USER_NAME: ${{ inputs.username }}
        FG_USER_PASS: ${{ inputs.password }}
        FG_UL_FILE: ${{ inputs.file-path }}
        FG_README_UPDATE: ${{ inputs.update-readme }}
        FG_UPLOAD_BUILD: 'TRUE'
      shell: bash
      run: uv run src/main.py
      working-directory: fg-updater-internal
