name: Pytest

on:
  push:
    paths:
      - "**.py"
      - .github/workflows/pytest.yml
      - pyproject.toml
  pull_request:
    paths:
      - "**.py"
      - .github/workflows/pytest.yml
      - pyproject.toml
  workflow_dispatch: null

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.12"
          - "3.11"
          - "3.10"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies with uv
        run: |
          pip install -U pip uv
          uv venv
          source .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
          uv pip install -e .[dev]
          uv pip install -e .[github-actions]

      - name: Test with pytest
        run: |
          pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
