name: Pytest

on:
  push:
    paths:
      - "**.py"
      - .github/workflows/pytest.yml
      - pyproject.toml
  pull_request:
    paths:
      - "**.py"
      - .github/workflows/pytest.yml
      - pyproject.toml
  workflow_dispatch: null

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.12"
          - "3.11"
          - "3.10"
          - "3.9"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        run: |
          pip3 install -U pip
          pip3 install .[dev]
          pip3 install .[github-actions]

      - name: Test code with pytest
        uses: pavelzw/pytest-action@v2
        with:
          emoji: true
          verbose: false
          job-summary: true
